highlighter: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

url: http://siteshwar.github.com/
description: 
twitter: SiteshwarV
github_id: siteshwar
gravatar_url: /images/rectangle.png
